"""empty message

Revision ID: 6adbedf1ad53
Revises: c1e4913ba48f
Create Date: 2019-03-22 09:21:28.757127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6adbedf1ad53'
down_revision = 'c1e4913ba48f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connects', sa.Column('type_id', sa.Integer(), nullable=True))
    op.drop_constraint('connects_category_id_fkey', 'connects', type_='foreignkey')
    op.create_foreign_key(None, 'connects', 'type', ['type_id'], ['id'])
    op.drop_column('connects', 'category_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connects', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'connects', type_='foreignkey')
    op.create_foreign_key('connects_category_id_fkey', 'connects', 'category', ['category_id'], ['id'])
    op.drop_column('connects', 'type_id')
    # ### end Alembic commands ###
