"""empty message

Revision ID: c1e4913ba48f
Revises: e9198eb4e209
Create Date: 2019-03-22 08:47:39.967004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1e4913ba48f'
down_revision = 'e9198eb4e209'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connects', sa.Column('source_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'connects', 'source', ['source_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'connects', type_='foreignkey')
    op.drop_column('connects', 'source_id')
    # ### end Alembic commands ###
